### ISSUE TITLE
Lag et api-endepunkt for å hente ned informasjon om partnere

### ISSUE THREAD

**Issue by tanettrimas** [javaBin/2023.javazone.no#7]
Den må inneholde:

- Navn
- Lenke til hjemmeside
- Lenke til ikon

**Comment by chrissearle** [comment]
En kommentar.

iOS sin SVG parser kan være vrient.

SVG som er ekte SVG pleier å gå fint - men - SVGer med embedded image feiler.

Når vi holdt på med embedding før - så var det ofte lettest å konvertere til png.

Vet ikke hvor ikon bilder skal lagres i år - men - import skript for det kanksje kan også lage en - si 100x100px png alpha i tillegg til mobilbruk?

Uansett - kan hjelpe med å teste dette fra iOS når vi er kommet så langt :)
